/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.PopupMenu;
import java.awt.color.ColorSpace;
import java.util.List;
import javax.swing.JScrollPane;
import org.jdesktop.swingx.JXHyperlink;



/**
 *
 * @author Alex
 */
public class MenuPrincipalAdministrador extends javax.swing.JFrame {
    private PanelAdministarProductos panelAdmProd;
    private PanelAdministrarClientes panelAdmClientes;
    private PanelAdministrarProveedores panelAdmProv;
    private PanelVenta panelVenta;
    private PanelAdministrarMarcas panelMarcas;
    private PanelAdministrarTiposProducto panelTiposProducto;
    private PanelAdministrarCategorias panelCategorias;
    private PanelAdministarLotes panelLotes;
    private PanelAdministarServicios panelServicios;
    private PanelAdministrarCuotas panelCuotas;
    private PanelCompra panelCompras;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalAdministrador() {
        initComponents();
        this.setTitle("B I E N V E N I D O ----- SISTEMA DE FACTURACIÓN CELLTEC");
        
        opcAdministrarClientes.setForeground(new Color(4, 36, 131));
        
        opcAdministrarProductos.setForeground(new Color(4, 36, 131));
        opcAdministrarProveedores.setForeground(new Color(4, 36, 131));
        opcAdministrarVentas.setForeground(new Color(4, 36, 131));
        opcReportes.setForeground(new Color(4, 36, 131));
        accesoDirecto.setForeground(Color.RED);
        accesoDirecto.setTitle("Accesos Directos");
        accesoDirecto.add(this.opcAdministrarClientes);
        accesoDirecto.add(this.opcAdministrarProductos);
        accesoDirecto.add(this.opcAdministrarProveedores);
        accesoDirecto.add(this.opcAdministrarVentas);
        accesoDirecto.add(this.opcReportes);
        this.setVisible(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitDivision = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        accesoDirecto = new org.jdesktop.swingx.JXTaskPane();
        opcAdministrarClientes = new org.jdesktop.swingx.JXHyperlink();
        opcAdministrarProveedores = new org.jdesktop.swingx.JXHyperlink();
        opcAdministrarVentas = new org.jdesktop.swingx.JXHyperlink();
        opcReportes = new org.jdesktop.swingx.JXHyperlink();
        opcAdministrarProductos = new org.jdesktop.swingx.JXHyperlink();
        opcReportes1 = new org.jdesktop.swingx.JXHyperlink();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitDivision.setDividerLocation(300);
        splitDivision.setDividerSize(0);

        opcAdministrarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/agent.png"))); // NOI18N
        opcAdministrarClientes.setText("Administrar Clientes");
        opcAdministrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAdministrarClientesActionPerformed(evt);
            }
        });

        opcAdministrarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/ID.png"))); // NOI18N
        opcAdministrarProveedores.setText("Administrar Proveedores");
        opcAdministrarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAdministrarProveedoresActionPerformed(evt);
            }
        });

        opcAdministrarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/dollar.png"))); // NOI18N
        opcAdministrarVentas.setText("Administrar Ventas");
        opcAdministrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAdministrarVentasActionPerformed(evt);
            }
        });

        opcReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/copy-item.png"))); // NOI18N
        opcReportes.setText("Cuentas por cobrar y pagar");
        opcReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcReportesActionPerformed(evt);
            }
        });

        opcAdministrarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/mobile.png"))); // NOI18N
        opcAdministrarProductos.setText("Administrar Productos");
        opcAdministrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAdministrarProductosActionPerformed(evt);
            }
        });

        opcReportes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/copy-item.png"))); // NOI18N
        opcReportes1.setText("Compras");
        opcReportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcReportes1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accesoDirecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcAdministrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcAdministrarProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcAdministrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcAdministrarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accesoDirecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(opcAdministrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcAdministrarProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcAdministrarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcAdministrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(opcReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        splitDivision.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());
        splitDivision.setRightComponent(jPanel2);

        getContentPane().add(splitDivision, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/shut-down.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/agent.png"))); // NOI18N
        jMenuItem2.setText("Administrar Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/copy-item.png"))); // NOI18N
        jMenuItem3.setText("Listar Clientes");
        jMenu2.add(jMenuItem3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/addressbook.png"))); // NOI18N
        jMenu5.setText("Reportes");
        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Productos");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/calculator.png"))); // NOI18N
        jMenuItem4.setText("Administrar Productos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/chat-02.png"))); // NOI18N
        jMenuItem5.setText("Administrar Categorías");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/copy-item.png"))); // NOI18N
        jMenuItem6.setText("Administrar Lotes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/container.png"))); // NOI18N
        jMenuItem9.setText("Administrar Tipos de Producto");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/lookup.png"))); // NOI18N
        jMenuItem10.setText("Administrar Marcas");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/cassette.png"))); // NOI18N
        jMenuItem11.setText("Administrar Servicios");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Proveedores");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/ID.png"))); // NOI18N
        jMenuItem7.setText("Administrar Proveedores");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/copy-item.png"))); // NOI18N
        jMenuItem8.setText("Listar Proveedores");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void opcAdministrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAdministrarClientesActionPerformed
        // TODO add your handling code here:
        panelAdmClientes = new PanelAdministrarClientes();
        JScrollPane topScrollPane = new JScrollPane(panelAdmClientes);
        this.splitDivision.setRightComponent(topScrollPane);
        //Dimension minimumSize = new Dimension(0, 0);
        //leftComponent.setMinimumSize(minimumSize);
        //this.splitDivision.setMinimumSize(minimumSize);
        this.repaint();
    }//GEN-LAST:event_opcAdministrarClientesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        panelAdmClientes = new PanelAdministrarClientes();
        this.splitDivision.setRightComponent(panelAdmClientes);
        this.repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        panelAdmProd = new PanelAdministarProductos();
        JScrollPane topScrollPane = new JScrollPane(panelAdmProd);
        this.splitDivision.setRightComponent(topScrollPane);
        this.repaint();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void opcAdministrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAdministrarProductosActionPerformed
        // TODO add your handling code here:
        panelAdmProd = new PanelAdministarProductos();
        JScrollPane topScrollPane = new JScrollPane(panelAdmProd);
        this.splitDivision.setRightComponent(topScrollPane);
        this.repaint();
    }//GEN-LAST:event_opcAdministrarProductosActionPerformed

    private void opcAdministrarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAdministrarProveedoresActionPerformed
        // TODO add your handling code here:
        panelAdmProv = new PanelAdministrarProveedores();
        this.splitDivision.setRightComponent(panelAdmProv);
        this.repaint();
    }//GEN-LAST:event_opcAdministrarProveedoresActionPerformed

    private void opcAdministrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAdministrarVentasActionPerformed
        // TODO add your handling code here:
        panelVenta = new PanelVenta();
        JScrollPane topScrollPane = new JScrollPane(panelVenta);
        this.splitDivision.setRightComponent(topScrollPane);
        this.repaint();
    }//GEN-LAST:event_opcAdministrarVentasActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
       
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        panelMarcas = new PanelAdministrarMarcas();
        this.splitDivision.setRightComponent(panelMarcas);
        this.repaint();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        panelTiposProducto = new PanelAdministrarTiposProducto();
        this.splitDivision.setRightComponent(panelTiposProducto);
        this.repaint();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        panelCategorias = new PanelAdministrarCategorias();
        this.splitDivision.setRightComponent(panelCategorias);
        this.repaint();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        //PanelAdministarLotes
        panelLotes = new PanelAdministarLotes();
        this.splitDivision.setRightComponent(panelLotes);
        this.repaint();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        panelServicios = new PanelAdministarServicios();
        this.splitDivision.setRightComponent(panelServicios);
        this.repaint();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void opcReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcReportesActionPerformed
        // TODO add your handling code here:
        panelCuotas = new PanelAdministrarCuotas();
        this.splitDivision.setRightComponent(panelCuotas);
        this.repaint();
    }//GEN-LAST:event_opcReportesActionPerformed

    private void opcReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcReportes1ActionPerformed
        // TODO add your handling code here:
        panelCompras = new PanelCompra();
        this.splitDivision.setRightComponent(panelCompras);
        this.repaint();
    }//GEN-LAST:event_opcReportes1ActionPerformed
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTaskPane accesoDirecto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jdesktop.swingx.JXHyperlink opcAdministrarClientes;
    private org.jdesktop.swingx.JXHyperlink opcAdministrarProductos;
    private org.jdesktop.swingx.JXHyperlink opcAdministrarProveedores;
    private org.jdesktop.swingx.JXHyperlink opcAdministrarVentas;
    private org.jdesktop.swingx.JXHyperlink opcReportes;
    private org.jdesktop.swingx.JXHyperlink opcReportes1;
    private javax.swing.JSplitPane splitDivision;
    // End of variables declaration//GEN-END:variables
}
